database:
  connection:
    type: mysql
    address: localhost
    port: 3306
    databaseName: insight
    username: 
    password: 
  tuning:
    cacheSize: 1000

excludedWorlds: []

logging:
  inventory: true
  drops: true
  logins: false
  vehicles: false
  leashes: false
  deaths: true
  pistons: false
  buckets: true
  hangings: true
  fire: true
  nature: true
  xp: true
  sheep: true
  farmland: true
