name: Insight
version: ${project.version}
load: POSTWORLD
author: Andy Shulman
main: com.amshulman.insight.InsightPlugin
softdepend: [WorldEdit, PlayerHeads]
website: http://dev.bukkit.org/bukkit-plugins/insight/
commands:
  insight:
    aliases: [i]
    usage: "Invalid usage! Please check http://dev.bukkit.org/bukkit-plugins/insight/ for help."

permissions:
  insight.lookup:
    children:
      insight: true
      insight.page: true
      insight.next: true
      insight.prev: true
  insight.wand:
    children:
      insight: true
      insight.page: true
      insight.next: true
      insight.prev: true
  insight.rollback:
    children:
      insight: true
  insight.tp:
    children:
      insight: true
